version: '3.8'

services:
  elasticsearch:
    build:
      context: compose/elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: te_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./compose/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - telemetry_elasticsearch

networks:
  telemetry_elasticsearch:
    driver: bridge

volumes:
  elasticsearch:
